name = "ncr-eform-api"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "smart-qa-db"
database_id = "e7fbe213-5e69-4bfa-bc63-bba305216402"

[vars]
ENVIRONMENT = "production"
