export const API_URL = import.meta.env.VITE_API_URL || 'https://ncr-eform-api.swifoods.workers.dev'
export const COMPANY_NAME = 'ศ.วรภัทร อินเตอร์ ฟู้ดส์ จำกัด'
export const COMPANY_NAME_EN = 'S.Woraphat Interfoods Co., Ltd.'
export const FORM_CODE_NCR = 'FM-QA-20'
export const FORM_CODE_CAPA = 'FM-QA-21'
export const FORM_REVISION = '00'
